-- SUB-QUERY
-- SELECT SUB-QUERY (SCALAR SUB-QUERY) 서브쿼리는 반드시 단일 행 리턴;
-- FROM SUB-QUERY
-- WHERE SUB-QUERY

SELECT MAX(B.가격) FROM 도서 A INNER JOIN 도서가격 B ON A.책번호 = B.책번호 
WHERE A.책명 = '자료구조';

--집합연산자 (4)
UNION      --NO DUPLICATES 
UNION ALL  --EXTRA DUPLICATES
INTERSECT  --
MINUS      -- MINUS COMMON PART WITH B FROM A
SELECT ENAME FROM EMP WHERE SAL <= 2000 AND SAL >= 1000;
SELECT ENAME FROM EMP WHERE SAL <= 2000 UNION SELECT ENAME FROM EMP WHERE SAL >= 1000;

SELECT ENAME FROM EMP WHERE SAL <= 2000 UNION ALL SELECT ENAME FROM EMP WHERE SAL >= 1000;

SELECT ENAME FROM EMP WHERE SAL <= 2000 INTERSECT SELECT ENAME FROM EMP WHERE SAL >= 1000;
